"""
In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s,
then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.

Return: The reverse complement sc of s.
"""


def complementing_strand_of_dna(dna_string: str):
    dna_string_c = dna_string[::-1]
    reverse_complement = ''
    for i in dna_string_c:
        if i == 'A':
            reverse_complement += 'T'
        elif i == 'T':
            reverse_complement += 'A'
        elif i == 'C':
            reverse_complement += 'G'
        elif i == 'G':
            reverse_complement += 'C'
    return reverse_complement
print(complementing_strand_of_dna('CCCACCTAGCCTAGGTAATATTGGGCAGTAGGTGACCGGCTACATGTAGACAATTACTTATCCTGGTTGTGACTGGTCGCTAGGATGGGGGAAATTCGTTCCATAACGGATGTTCAGATGGTCAAGGAGACCCGTCCGAGATGTTAATTACGTCAGGACTGTCCAGGGCCTGAGGCCGGTAGTTGACCGGTGGATTATACGCAAGAGTTATAGTATTGTAGGGGAGAACAAACCAACCACGACACATCCTCTTCATTCGACCTGGCATTGCAGTCGGAGCGAATGCCCAGCTACTTCCTACGTCCAGTAAGCCTTGTAGTTCCAATGGGAGTGAGCCAGGTCATGGAATCAATTTAACATAGCGATCCTACAGAGGGCGACCCACAATCAGAGATTAGATACTGTCGGAATCTCCCTAAGTTCTCTGCTATCATAGCGGACCTTGTTTGTTCGGACACATGGCTATTATGAATATTGGCTAACACACTCTCGCGACAGTGTGCCGCAGGCCAGATAGCGACTGTCCTAGGTCTCAGTCTACTTCCCGAGACGGCTCTTCTGGACACGGTCGGCGGTACTGAGTTAGCTTTGTGATACAGCGTTGTATCAAGGATGAACGAATGTATTACTGAGAAATTCTGTTTTTGGTTAGATATGACAGAACCGCACAAGTCTCCCGATCGAAGGCGCCTCTGCTACCGCAACGGCGACAGATCTTGAGGGCGGAGGCCTGTAGCTCATTTACTTGATTAGGACCGGAACGGCTTATGCCGCGCGGGAAGAGGGCGAACCATCATCGGAT'))